/*ESCREVA UM CÓDIGO ONDE TEMOS  O CONTROLE DE UM PETSHOP, A MAQUINA DE BANHO DOS PETS DEVE TER AS SEGUINTES OPERAÇÕES:
*   DAR BANHO NO PET
*   ABASTECER COM ÁGUA
*   ABTASECER COM SHAMPOO
*   VERIFICAR O NOVEL DA ÁGUA
*   VERIFICAR O NIVEL DE SHAMPOO
*   VEVERIFICAR SE TEM PET NO BANHO
*    COLOCAR PET NA MÁQUINA
*
* REGRAS DE NEGÓCIO
* A MÁQUINA DE BAHO DEVE PERMITIR SOMENTE 1 PET POR VEZ
* CADA BANHO REALIZADO IRÁ CONSUMIR 10 LITROS DE AGUA E 2 LITROS DE SHAMPOO
* Á MÁQUINA TEM CAPACIDADE MAXIMA DE 30 LITROS DE AGUA E 10 LITROS DE SHAMPOO
* SE O PET FOR RETIRADO DA MAQUINA SEM ESTAR LIMPO SERÁ NECESSÁRIO LIMPAR A MÁQUINA PARA PERMITIR A ENTRADA DE OUTRO PET
* A LIMPEZA DA MÁQUINA IRÁ CONSUMIR 3 LITROS DE AGUA E 1 LITRO DE SHAMPOO
* O ABASTECIMENTO DE ÁGUA E SHAMPOO DEVE PERMITIR 2 LITROS POR VEZ QUE FOR ACIONADO.
*
 */

public class Exercicio_03 {
}
